# coding:utf8

# 机动车损失保险
def _damage_insurance_namt_20(Vhl_NNewPurchaseValue, _carDamageBenchMarkPremium,
                              SY_Base_TInsrncBgnTm, SY_Base_TInsrncEndTm, CAppNo='', hebao_premium={}):
    carDamage_Premium = hebao_premium.get('carDamagePremium', '')

    body = """
    {index: '20', selected: 'false', status: 'UNCHANGED',
                  attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                                    {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                                    {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NSeqNo', newValue: '20', bakValue: '20', value: '20'},
                                    {name: 'Cvrg.CCvrgNo', newValue: '030006', bakValue: '030006', value: '030006'},
                                    {name: 'Cvrg.NAmt', newValue: '%(Vhl_NNewPurchaseValue)s', bakValue: '%(Vhl_NNewPurchaseValue)s', value: '%(Vhl_NNewPurchaseValue)s'},
                                    {name: 'Cvrg.NRate', newValue: '0', bakValue: '0', value: '0'},
                                    {name: 'Cvrg.NBasePrm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NBefPrm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NCalcPrm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NPrm', newValue: '%(carDamage_Premium)s', bakValue: '%(carDamage_Premium)s', value: '%(carDamage_Premium)s'},
                                    {name: 'Cvrg.NBefAnnPrm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NCalcAnnPrm', newValue: '%(carDamage_Premium)s', bakValue: '%(carDamage_Premium)s', value: '%(carDamage_Premium)s'},
                                    {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                                    {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                                     value: '%(SY_Base_TInsrncBgnTm)s'},
                                    {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                                     value: '%(SY_Base_TInsrncEndTm)s'},
                                    {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                                    {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                                    {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NIndemLmt', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CDductMrk', newValue: '%(_carDamageBenchMarkPremium)s', bakValue: '%(_carDamageBenchMarkPremium)s', value: '%(_carDamageBenchMarkPremium)s'},
                                    {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CIndemLmtLvl', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NLiabDaysLmt', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NPerAmt', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NDductRate', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CResvTxt13', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.CResvTxt30', newValue: '1.0', bakValue: '1.0', value: '1.0'},
                                    {name: 'Cvrg.NDductPrm', newValue: '3714.449085', bakValue: '3714.449085', value: '3714.449085'},
                                    {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '',value: ''},
                                    {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                                    {name: 'Cvrg.NResvNum30', newValue: '177.89', bakValue: '177.89', value: '177.89'},
                                    {name: 'Cvrg.NResvNum29', newValue: '1185.94', bakValue: '1185.94', value: '1185.94'},
                                    {name: 'Cvrg.NResvNum28', newValue: '273.68', bakValue: '273.68', value: '273.68'}]},
    """ % {'Vhl_NNewPurchaseValue': Vhl_NNewPurchaseValue, 'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm,
           'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm, '_carDamageBenchMarkPremium': _carDamageBenchMarkPremium,
           'CAppNo': CAppNo, 'carDamage_Premium': carDamage_Premium}

    return body


# 三者险
def _third_party_insurance_15(_otherHurtPremium, _otherHurtBenchMarkPremium,
                              SY_Base_TInsrncBgnTm,
                              SY_Base_TInsrncEndTm, CAppNo='', hebao_premium={}):
    otherHurt_Premium = hebao_premium.get('otherHurtPremium', '')
    otherHurtPremium = _otherHurtPremium.get("Amount")
    if int(otherHurtPremium)/10000 == 50:
        Cvrg_CIndemLmtLvl = "306006009"
    elif int(otherHurtPremium)/10000 == 100:
        Cvrg_CIndemLmtLvl = "306006014"
    else:
        Cvrg_CIndemLmtLvl = "306006014"

    body = """
{index: '15', selected: 'false', status: 'UNCHANGED',
              attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                                {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                                {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NSeqNo', newValue: '15', bakValue: '15', value: '15'},
                                {name: 'Cvrg.CCvrgNo', newValue: '030018', bakValue: '030018', value: '030018'},
                                {name: 'Cvrg.NAmt', newValue: '%(otherHurtPremium)s', bakValue: '%(otherHurtPremium)s', value: '%(otherHurtPremium)s'},
                                {name: 'Cvrg.NRate', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NBasePrm', newValue: '1049.1', bakValue: '1049.1', value: '1049.1'},
                                {name: 'Cvrg.NBefPrm', newValue: '1614.00', bakValue: '1614.00', value: '1614.00'},
                                {name: 'Cvrg.NCalcPrm', newValue: '0.00', bakValue: '0.00', value: '0.00'},
                                {name: 'Cvrg.NPrm', newValue: '%(otherHurt_Premium)s', bakValue: '%(otherHurt_Premium)s', value: '%(otherHurt_Premium)s'},
                                {name: 'Cvrg.NBefAnnPrm', newValue: '1614', bakValue: '1614', value: '1614'},
                                {name: 'Cvrg.NCalcAnnPrm', newValue: '%(otherHurt_Premium)s', bakValue: '%(otherHurt_Premium)s', value: '%(otherHurt_Premium)s'},
                                {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                                 value: '%(SY_Base_TInsrncBgnTm)s'},
                                {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                                 value: '%(SY_Base_TInsrncEndTm)s'},
                                {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NIndemLmt', newValue: '%(otherHurtPremium)s', bakValue: '%(otherHurtPremium)s', value: '%(otherHurtPremium)s'},
                                {name: 'Cvrg.CDductMrk', newValue: '%(_otherHurtBenchMarkPremium)s', bakValue: '%(_otherHurtBenchMarkPremium)s', value: '%(_otherHurtBenchMarkPremium)s'},
                                {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CIndemLmtLvl', newValue: '%(Cvrg_CIndemLmtLvl)s', bakValue: '%(Cvrg_CIndemLmtLvl)s',
                                 value: '%(Cvrg_CIndemLmtLvl)s'}, {name: 'Cvrg.NLiabDaysLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPerAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductRate', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt13', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt30', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductPrm', newValue: '174.92', bakValue: '174.92', value: '174.92'},
                                {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NResvNum30', newValue: '157.37', bakValue: '157.37', value: '157.37'},
                                {name: 'Cvrg.NResvNum29', newValue: '1049.1', bakValue: '1049.1', value: '1049.1'},
                                {name: 'Cvrg.NResvNum28', newValue: '242.1', bakValue: '242.1', value: '242.1'}]},

    """ % {'otherHurtPremium': _otherHurtPremium.get("Amount"), 'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm,
           'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm, '_otherHurtBenchMarkPremium': _otherHurtBenchMarkPremium,
           'CAppNo': CAppNo, 'otherHurt_Premium': otherHurt_Premium, 'Cvrg_CIndemLmtLvl': Cvrg_CIndemLmtLvl}

    return body


# 车上人员险（司机）
def _driver_liability_insurance_13(_driverDutyPremium, _driverDutyBenchMarkPremium,
                                   SY_Base_TInsrncBgnTm,
                                   SY_Base_TInsrncEndTm, CAppNo='', hebao_premium={}):
    driverDuty_Premium = hebao_premium.get('driverDutyPremium', '')
    body = """
    {index: '13', selected: 'false', status: 'UNCHANGED',
              attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                                {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                                {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NSeqNo', newValue: '13', bakValue: '13', value: '13'},
                                {name: 'Cvrg.CCvrgNo', newValue: '030210', bakValue: '030210', value: '030210'},
                                {name: 'Cvrg.NAmt', newValue: '10000.00', bakValue: '10000.00', value: '10000.00'},
                                {name: 'Cvrg.NRate', newValue: '0.26', bakValue: '0.26', value: '0.26'},
                                {name: 'Cvrg.NBasePrm', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NBefPrm', newValue: '40.00', bakValue: '40.00', value: '40.00'},
                                {name: 'Cvrg.NCalcPrm', newValue: '0.00', bakValue: '0.00', value: '0.00'},
                                {name: 'Cvrg.NPrm', newValue: '%(driverDuty_Premium)s', bakValue: '%(driverDuty_Premium)s', value: '%(driverDuty_Premium)s'},
                                {name: 'Cvrg.NBefAnnPrm', newValue: '40', bakValue: '40', value: '40'},
                                {name: 'Cvrg.NCalcAnnPrm', newValue: '%(driverDuty_Premium)s', bakValue: '%(driverDuty_Premium)s', value: '%(driverDuty_Premium)s'},
                                {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                                 value: '%(SY_Base_TInsrncBgnTm)s'},
                                {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                                 value: '%(SY_Base_TInsrncEndTm)s'},
                                {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CDductMrk', newValue: '%(_driverDutyBenchMarkPremium)s', bakValue: '%(_driverDutyBenchMarkPremium)s', value: '%(_driverDutyBenchMarkPremium)s'},
                                {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CIndemLmtLvl', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NLiabDaysLmt', newValue: '1', bakValue: '1', value: '1'},
                                {name: 'Cvrg.NPerAmt', newValue: '%(driverDutyPremium)s', bakValue: '%(driverDutyPremium)s', value: '%(driverDutyPremium)s'},
                                {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductRate', newValue: '0.15', bakValue: '0.15', value: '0.15'},
                                {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt13', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt30', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductPrm', newValue: '4.34', bakValue: '4.34', value: '4.34'},
                                {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NResvNum30', newValue: '3.9', bakValue: '3.9', value: '3.9'},
                                {name: 'Cvrg.NResvNum29', newValue: '26', bakValue: '26', value: '26'},
                                {name: 'Cvrg.NResvNum28', newValue: '6', bakValue: '6', value: '6'}]},
    """ % {'driverDutyPremium': _driverDutyPremium.get("Amount"), 'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm,
           'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm, '_driverDutyBenchMarkPremium': _driverDutyBenchMarkPremium,
           'CAppNo': CAppNo, 'driverDuty_Premium': driverDuty_Premium}

    return body


# 车上人员险（乘客）
def _pass_liability_insurance_14(_passengerDutyPremium, seats,
                                 _passengerBenchMarkPremium, SY_Base_TInsrncBgnTm,
                                 SY_Base_TInsrncEndTm, CAppNo='', hebao_premium={}):
    peramount = _passengerDutyPremium.get("Amount")  # 单乘客钱数
    allamount = str(float(int(seats - 1) * int(peramount)))
    passengerDuty_Premium = hebao_premium.get('passengerDutyPremium', '')

    body = """
    {index: '14', selected: 'false', status: 'UNCHANGED',
              attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                                {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                                {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NSeqNo', newValue: '14', bakValue: '14', value: '14'},
                                {name: 'Cvrg.CCvrgNo', newValue: '030212', bakValue: '030212', value: '030212'},
                                {name: 'Cvrg.NAmt', newValue: '%(allamount)s', bakValue: '%(allamount)s', value: '%(allamount)s'},
                                {name: 'Cvrg.NRate', newValue: '0.169', bakValue: '0.169', value: '0.169'},
                                {name: 'Cvrg.NBasePrm', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NBefPrm', newValue: '104.00', bakValue: '104.00', value: '104.00'},
                                {name: 'Cvrg.NCalcPrm', newValue: '0.00', bakValue: '0.00', value: '0.00'},
                                {name: 'Cvrg.NPrm', newValue: '%(passengerDuty_Premium)s', bakValue: '%(passengerDuty_Premium)s', value: '%(passengerDuty_Premium)s'},
                                {name: 'Cvrg.NBefAnnPrm', newValue: '104', bakValue: '104', value: '104'},
                                {name: 'Cvrg.NCalcAnnPrm', newValue: '%(passengerDuty_Premium)s', bakValue: '%(passengerDuty_Premium)s', value: '%(passengerDuty_Premium)s'},
                                {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                                 value: '%(SY_Base_TInsrncBgnTm)s'},
                                {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                                 value: '%(SY_Base_TInsrncEndTm)s'},
                                {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CDductMrk', newValue: '%(_passengerBenchMarkPremium)s', bakValue: '%(_passengerBenchMarkPremium)s', value: '%(_passengerBenchMarkPremium)s'},
                                {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CIndemLmtLvl', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NLiabDaysLmt', newValue: '4', bakValue: '4', value: '4'},
                                {name: 'Cvrg.NPerAmt', newValue: '%(passengerDutyPremium)s', bakValue: '%(passengerDutyPremium)s', value: '%(passengerDutyPremium)s'},
                                {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductRate', newValue: '0.15', bakValue: '0.15', value: '0.15'},
                                {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt13', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt30', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductPrm', newValue: '11.27', bakValue: '11.27', value: '11.27'},
                                {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NResvNum30', newValue: '10.14', bakValue: '10.14', value: '10.14'},
                                {name: 'Cvrg.NResvNum29', newValue: '67.6', bakValue: '67.6', value: '67.6'},
                                {name: 'Cvrg.NResvNum28', newValue: '15.6', bakValue: '15.6', value: '15.6'}]},
    """ % {'passengerDutyPremium': _passengerDutyPremium.get("Amount"), 'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm,
           'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm, '_passengerBenchMarkPremium': _passengerBenchMarkPremium,
           'allamount': allamount,
           'CAppNo': CAppNo, 'passengerDuty_Premium': passengerDuty_Premium}
    return body


# 盗抢险
def _theft_insurance_namt_18(Vhl_NNewPurchaseValue, _carTheftBenchMarkPremium,
                             SY_Base_TInsrncBgnTm, SY_Base_TInsrncEndTm, CAppNo='', hebao_premium={}):
    carTheft_Premium = hebao_premium.get('carTheftPremium', '')
    body = """
    {index: '18', selected: 'false', status: 'UNCHANGED',
              attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                                {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                                {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NSeqNo', newValue: '18', bakValue: '18', value: '18'},
                                {name: 'Cvrg.CCvrgNo', newValue: '030102', bakValue: '030102', value: '030102'},
                                {name: 'Cvrg.NAmt', newValue: '%(Vhl_NNewPurchaseValue)s', bakValue: '%(Vhl_NNewPurchaseValue)s', value: '%(Vhl_NNewPurchaseValue)s'},
                                {name: 'Cvrg.NRate', newValue: '0.273', bakValue: '0.273', value: '0.273'},
                                {name: 'Cvrg.NBasePrm', newValue: '78', bakValue: '78', value: '78'},
                                {name: 'Cvrg.NBefPrm', newValue: '440.94', bakValue: '440.94', value: '440.94'},
                                {name: 'Cvrg.NCalcPrm', newValue: '0.00', bakValue: '0.00', value: '0.00'},
                                {name: 'Cvrg.NPrm', newValue: '%(carTheft_Premium)s', bakValue: '%(carTheft_Premium)s', value: '%(carTheft_Premium)s'},
                                {name: 'Cvrg.NBefAnnPrm', newValue: '440.94', bakValue: '440.94', value: '440.94'},
                                {name: 'Cvrg.NCalcAnnPrm', newValue: '%(carTheft_Premium)s', bakValue: '%(carTheft_Premium)s', value: '%(carTheft_Premium)s'},
                                {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                                 value: '%(SY_Base_TInsrncBgnTm)s'},
                                {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                                 value: '%(SY_Base_TInsrncEndTm)s'},
                                {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                                {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CDductMrk', newValue: '%(_carTheftBenchMarkPremium)s', bakValue: '%(_carTheftBenchMarkPremium)s', value: '%(_carTheftBenchMarkPremium)s'},
                                {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CIndemLmtLvl', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NLiabDaysLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPerAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductRate', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt13', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.CResvTxt30', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NDductPrm', newValue: '63.72', bakValue: '63.72', value: '63.72'},
                                {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                                {name: 'Cvrg.NResvNum30', newValue: '57.32', bakValue: '57.32', value: '57.32'},
                                {name: 'Cvrg.NResvNum29', newValue: '286.61', bakValue: '286.61', value: '286.61'},
                                {name: 'Cvrg.NResvNum28', newValue: '88.19', bakValue: '88.19', value: '88.19'}]},
    """ % {'Vhl_NNewPurchaseValue': Vhl_NNewPurchaseValue, 'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm,
           'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm, '_carTheftBenchMarkPremium': _carTheftBenchMarkPremium,
           'CAppNo': CAppNo, 'carTheft_Premium': carTheft_Premium}

    return body


# 自燃险
def _autoignition_insurance_namt_5(Vhl_NNewPurchaseValue,
                                   _carFireBrokenBenchMarkPremium22,
                                   SY_Base_TInsrncBgnTm,
                                   SY_Base_TInsrncEndTm, CAppNo='', hebao_premium={}):
    carFire_Premium = hebao_premium.get('carFirePremium', '')
    body = """
    {index: '5', selected: 'false', status: 'UNCHANGED',
      attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                        {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                        {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NSeqNo', newValue: '5', bakValue: '5', value: '5'},
                        {name: 'Cvrg.CCvrgNo', newValue: '030057', bakValue: '030057', value: '030057'},
                        {name: 'Cvrg.NAmt', newValue: '%(Vhl_NNewPurchaseValue)s', bakValue: '%(Vhl_NNewPurchaseValue)s', value: '%(Vhl_NNewPurchaseValue)s'},
                        {name: 'Cvrg.NRate', newValue: '0.13', bakValue: '0.13', value: '0.13'},
                        {name: 'Cvrg.NBasePrm', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NBefPrm', newValue: '151.75', bakValue: '151.75', value: '151.75'},
                        {name: 'Cvrg.NCalcPrm', newValue: '0.00', bakValue: '0.00', value: '0.00'},
                        {name: 'Cvrg.NPrm', newValue: '%(carFire_Premium)s', bakValue: '%(carFire_Premium)s', value: '%(carFire_Premium)s'},
                        {name: 'Cvrg.NBefAnnPrm', newValue: '151.75', bakValue: '151.75', value: '151.75'},
                        {name: 'Cvrg.NCalcAnnPrm', newValue: '%(carFire_Premium)s', bakValue: '%(carFire_Premium)s', value: '%(carFire_Premium)s'},
                        {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                         value: '%(SY_Base_TInsrncBgnTm)s'},
                        {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                         value: '%(SY_Base_TInsrncEndTm)s'},
                        {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CDductMrk', newValue: '%(_carFireBrokenBenchMarkPremium22)s', bakValue: '%(_carFireBrokenBenchMarkPremium22)s', value: '%(_carFireBrokenBenchMarkPremium22)s'},
                        {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CIndemLmtLvl', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NLiabDaysLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductRate', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt13', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt30', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductPrm', newValue: '21.93', bakValue: '21.93', value: '21.93'},
                        {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NResvNum30', newValue: '19.73', bakValue: '19.73', value: '19.73'},
                        {name: 'Cvrg.NResvNum29', newValue: '98.64', bakValue: '98.64', value: '98.64'},
                        {name: 'Cvrg.NResvNum28', newValue: '30.35', bakValue: '30.35', value: '30.35'}]},
    """ % {'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm, 'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm,
           '_carFireBrokenBenchMarkPremium22': _carFireBrokenBenchMarkPremium22,
           'Vhl_NNewPurchaseValue': Vhl_NNewPurchaseValue,
           'CAppNo': CAppNo, 'carFire_Premium': carFire_Premium}

    return body


# 玻璃破碎险
def _crush_insurance_namt_8(NResvNum2, SY_Base_TInsrncBgnTm, SY_Base_TInsrncEndTm, glassBrokenPremium, CAppNo='',
                            hebao_premium={}):
    glassBroken_Premium = hebao_premium.get('glassBrokenPremium', '')
    body = """
    {index: '8', selected: 'false', status: 'UNCHANGED',
              attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                        {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                        {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NSeqNo', newValue: '8', bakValue: '8', value: '8'},
                        {name: 'Cvrg.CCvrgNo', newValue: '030105', bakValue: '030105', value: '030105'},
                        {name: 'Cvrg.NAmt', newValue: '%(NResvNum2)s', bakValue: '%(NResvNum2)s', value: '%(NResvNum2)s'},
                        {name: 'Cvrg.NRate', newValue: '0.1235', bakValue: '0.1235', value: '0.1235'},
                        {name: 'Cvrg.NBasePrm', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NBefPrm', newValue: '170.81', bakValue: '170.81', value: '170.81'},
                        {name: 'Cvrg.NCalcPrm', newValue: '0.00', bakValue: '0.00', value: '0.00'},
                        {name: 'Cvrg.NPrm', newValue: '%(glassBroken_Premium)s', bakValue: '%(glassBroken_Premium)s', value: '%(glassBroken_Premium)s'},
                        {name: 'Cvrg.NBefAnnPrm', newValue: '170.81', bakValue: '170.81', value: '170.81'},
                        {name: 'Cvrg.NCalcAnnPrm', newValue: '%(glassBroken_Premium)s', bakValue: '%(glassBroken_Premium)s', value: '%(glassBroken_Premium)s'},
                        {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                         value: '%(SY_Base_TInsrncBgnTm)s'},
                        {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                         value: '%(SY_Base_TInsrncEndTm)s'},
                        {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CDductMrk', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CIndemLmtLvl', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NLiabDaysLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductRate', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt13', newValue: '%(glassBrokenPremium)s', bakValue: '%(glassBrokenPremium)s', value: '%(glassBrokenPremium)s'},
                        {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt30', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductPrm', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NResvNum30', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NResvNum29', newValue: '111.03', bakValue: '111.03', value: '111.03'},
                        {name: 'Cvrg.NResvNum28', newValue: '0', bakValue: '0', value: '0'}]},
    """ % {'glassBrokenPremium': glassBrokenPremium, 'NResvNum2': NResvNum2,
           'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm,
           'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm,
           'CAppNo': CAppNo, 'glassBroken_Premium': glassBroken_Premium}

    return body


# 涉水险
def _wade_insurance_namt_10(Vhl_NNewPurchaseValue, _engineWadingBenchMarkPremium22,
                            SY_Base_TInsrncBgnTm, SY_Base_TInsrncEndTm, CAppNo='', hebao_premium={}):
    engineWading_Premium = hebao_premium.get('engineWadingPremium', '')

    body = """
    {index: '10', selected: 'false', status: 'UNCHANGED',
              attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                        {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                        {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NSeqNo', newValue: '10', bakValue: '10', value: '10'},
                        {name: 'Cvrg.CCvrgNo', newValue: '030203', bakValue: '030203', value: '030203'},
                        {name: 'Cvrg.NAmt', newValue: '%(Vhl_NNewPurchaseValue)s', bakValue: '%(Vhl_NNewPurchaseValue)s', value: '%(Vhl_NNewPurchaseValue)s'},
                        {name: 'Cvrg.NRate', newValue: '5', bakValue: '5', value: '5'},
                        {name: 'Cvrg.NBasePrm', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NBefPrm', newValue: '91.23', bakValue: '91.23', value: '91.23'},
                        {name: 'Cvrg.NCalcPrm', newValue: '0.00', bakValue: '0.00', value: '0.00'},
                        {name: 'Cvrg.NPrm', newValue: '%(engineWading_Premium)s', bakValue: '%(engineWading_Premium)s', value: '%(engineWading_Premium)s'},
                        {name: 'Cvrg.NBefAnnPrm', newValue: '91.23', bakValue: '91.23', value: '91.23'},
                        {name: 'Cvrg.NCalcAnnPrm', newValue: '%(engineWading_Premium)s', bakValue: '%(engineWading_Premium)s', value: '%(engineWading_Premium)s'},
                        {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                         value: '%(SY_Base_TInsrncBgnTm)s'},
                        {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                         value: '%(SY_Base_TInsrncEndTm)s'},
                        {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CDductMrk', newValue: '%(_engineWadingBenchMarkPremium22)s', bakValue: '%(_engineWadingBenchMarkPremium22)s', value: '%(_engineWadingBenchMarkPremium22)s'},
                        {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CIndemLmtLvl', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NLiabDaysLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductRate', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt13', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt30', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductPrm', newValue: '9.89', bakValue: '9.89', value: '9.89'},
                        {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NResvNum30', newValue: '8.89', bakValue: '8.89', value: '8.89'},
                        {name: 'Cvrg.NResvNum29', newValue: '59.3', bakValue: '59.3', value: '59.3'},
                        {name: 'Cvrg.NResvNum28', newValue: '13.68', bakValue: '13.68', value: '13.68'}]},
    """ % {'Vhl_NNewPurchaseValue': Vhl_NNewPurchaseValue, 'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm,
           'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm,
           '_engineWadingBenchMarkPremium22': _engineWadingBenchMarkPremium22,
           'CAppNo': CAppNo, 'engineWading_Premium': engineWading_Premium}
    return body


# 划痕险
def _scratch_insurance_namt_19(_carNickPremium, _carNickBenchMarkPremium,
                               SY_Base_TInsrncBgnTm,
                               SY_Base_TInsrncEndTm, CAppNo='', hebao_premium={}):
    carNick_Premium = hebao_premium.get('carNickPremium', '')
    body = """
    {index: '19', selected: 'false', status: 'UNCHANGED',
              attributeVoList: [{name: 'Cvrg.NResvNum2', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NResvNum3', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDisCoef', newValue: '1.000000', bakValue: '1.000000', value: '1.000000'},
                        {name: 'Cvrg.CPkId', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CAppNo', newValue: '%(CAppNo)s', bakValue: '%(CAppNo)s', value: '%(CAppNo)s'},
                        {name: 'Cvrg.CPlyNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NEdrPrjNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CEdrNo', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NSeqNo', newValue: '19', bakValue: '19', value: '19'},
                        {name: 'Cvrg.CCvrgNo', newValue: '030106', bakValue: '030106', value: '030106'},
                        {name:'Cvrg.NAmt',newValue:'%(scratch_insurance)s',bakValue:'%(scratch_insurance)s',value:'%(scratch_insurance)s'},
                        {name: 'Cvrg.NRate', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NBasePrm', newValue: '396.5', bakValue: '396.5', value: '396.5'},
                        {name: 'Cvrg.NBefPrm', newValue: '610.00', bakValue: '610.00', value: '610.00'},
                        {name: 'Cvrg.NCalcPrm', newValue: '0.00', bakValue: '0.00', value: '0.00'},
                        {name: 'Cvrg.NPrm', newValue: '%(carNick_Premium)s', bakValue: '%(carNick_Premium)s', value: '%(carNick_Premium)s'},
                        {name: 'Cvrg.NBefAnnPrm', newValue: '610', bakValue: '610', value: '610'},
                        {name: 'Cvrg.NCalcAnnPrm', newValue: '%(carNick_Premium)s', bakValue: '%(carNick_Premium)s', value: '%(carNick_Premium)s'},
                        {name: 'Cvrg.TPrmChgTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDutPrm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CRemark', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCancelMrk', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.TBgnTm', newValue: '%(SY_Base_TInsrncBgnTm)s', bakValue: '%(SY_Base_TInsrncBgnTm)s',
                         value: '%(SY_Base_TInsrncBgnTm)s'},
                        {name: 'Cvrg.TEndTm', newValue: '%(SY_Base_TInsrncEndTm)s', bakValue: '%(SY_Base_TInsrncEndTm)s',
                         value: '%(SY_Base_TInsrncEndTm)s'},
                        {name: 'Cvrg.NAmtVar', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NPrmVar', newValue: '0', bakValue: '0', value: '0'},
                        {name: 'Cvrg.NCalcPrmVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NIndemVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CLatestMrk', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCrtCde', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.TCrtTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CUpdCde', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.TUpdTm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CRowId', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CDductMrk', newValue: '%(_carNickBenchMarkPremium)s', bakValue: '%(_carNickBenchMarkPremium)s', value: '%(_carNickBenchMarkPremium)s'},
                        {name: 'Cvrg.CCustClCtnt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CTgtTyp', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NTgtQty', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CIndemLmtLvl', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NLiabDaysLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPerPrm', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NOnceIndemLmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NSavingAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CTgtNme', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductRate', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CDductDesc', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductAmt', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CCustCvrgNme', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt13', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt12', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.CResvTxt30', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NDductPrm', newValue: '66.11', bakValue: '66.11', value: '66.11'},
                        {name: 'Cvrg.CGlassSpecialMaterial', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NPureRiskPremium', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NNonDeductiblePrmVar', newValue: '', bakValue: '', value: ''},
                        {name: 'Cvrg.NResvNum30', newValue: '59.48', bakValue: '59.48', value: '59.48'},
                        {name: 'Cvrg.NResvNum29', newValue: '396.5', bakValue: '396.5', value: '396.5'},
                        {name: 'Cvrg.NResvNum28', newValue: '91.5', bakValue: '91.5', value: '91.5'}]},
    """ % {'scratch_insurance': _carNickPremium.get("Amount"), 'SY_Base_TInsrncBgnTm': SY_Base_TInsrncBgnTm,
           'SY_Base_TInsrncEndTm': SY_Base_TInsrncEndTm, '_carNickBenchMarkPremium': _carNickBenchMarkPremium,
           'CAppNo': CAppNo, 'carNick_Premium': carNick_Premium}
    return body
