# -*- coding:utf-8 -*-
__author__ = 'weikai'
import sys, json
from string import Template
import urllib, datetime
from request_xinda.xd_parse import parse_split_str, format_number
from  common.timeUtil import getlatedate
from request_xinda.xd_insuranceType import get_xd_insurance
from request_huanong.hn_util import calc_user_years

reload(sys)
sys.setdefaultencoding('utf-8')


def xd_get_first_body(permium_dict):
    body = '''
    preceptNoBC=
    &newMotorCade=0
    &loginRiskCode=0500
    &RiskCode=0500
    &AgentCode=U03122000011
    &businessNatureFlag=FG
    &loginComCode=03120000
    &loginComCodeSub=03
    &editType=EditType_ProposalInput
    &isCIInsure=1
    &isBIInsure=1
    &platformComCodeCST=QG
    &isInitRiskCodeCI=1
    &isInitRiskCodeBI=1
    &inputRiskCI=1
    &inputRiskBI=1
    &isInsureFlagBC=1
    &biInsureComCode=QG
    &ciInsureComCode=QG
    &isCarShipTaxJZ=1
    &tabLoadFlag=1
    &currentDate=${currentDate}
    &jfcdFlagCI=1
    &jfcdFlagBI=1
    &notTogetherFlag=
    &isPremiuTest=true
    &renewalSwitch=1
    &EpolicyComSwitch=0
    &CheckAppliCertiCodeFlag=0
    &EFlagBC=
    &EPolicyStartDate=0
    &operateDateFG=1
    &operateDateLN=1
    &checkUniteComCode=1
    &modelCodeFG=
    &FGComCodeSwitch=1
    &FGComCodeSwitchNew=1
    &renewalSwitchNew=1
    &isCommissionToPlatform=1
    &CheckEndorStatus=
    &RelCheckEndorStatus=
    &EndorType=
    &includeFilePathType=tbcb
    &inputType=31
    &inputSource1=InputSource_New
    &copyRiskCodeCI=
    &copyRiskCodeBI=
    &combNoBC=
    &NewClauseSwitch=0
    &NewClauseStartDate=0
    &UIYHComCodeSwitch=1
    &UIVINComCodeSwitch=1
    &CIBIMergeComCodeSwitch=0
    &riskCodeCI=0507
    &startDateCI=${startDateCI}
    &endDateCI=${endDateCI}
    &immeValidStartDateCI=${immeValidStartDateCI}
    &startHourCI=19
    &immeValidEndDateCI=${immeValidEndDateCI}
    &endHourCI=19
    &payMethodCI=01
    &riskCodeBI=0518
    &startDateBI=${startDateBI}
    &endDateBI=${endDateBI}
    &immeValidStartDateBI=${immeValidStartDateBI}
    &startHourBI=19
    &immeValidEndDateBI=${immeValidEndDateBI}
    &endHourBI=24
    &payMethodBI=01
    &ciProposalType=1
    &unProposalReason=02
    &ciinsurerCompany=信达财产保险股份有限公司
    &CIInsurerType=1
    &undefind=
    &ciInsurerPolicyNo=
    &immeValidFlagZJ=2
    &immeValidSpecialFlag=false
    &intCountBC=0
    &checkPayStartDate=${checkPayStartDate}
    &operateDateCI=${operateDateCI}
    &operateDateBI=${operateDateCI}
    &PeriodInfo_FlagBC=
    &renewalimmeValidFlag=0
    &FrameNo=${frameNo}
    &EngineNo=${engineNo}
    &AppliName=${AppliName}
    &queryFlag=1
    &isVINQuery=1
    &VINQueryResult=1
    &carAgeBC=
    &newCarPriceRiseBC=25
    &newCarPriceFallBC=10
    &damagedFactorGradeBIPlatFrom=
    &damagedFactorGradeBIHidden=0
    &carOwnerNature1BC=${carOwnerNature1BC}
    &carOwnerBC=${AppliName}
    &carOwnerIdentifyTypeCI=${carOwnerIdentifyTypeCI}
    &carOwnerIdentifyNumberCI=${IdentifyNumber}
    &licenseNoBC=${licenseNo}
    &frameNoBC=${frameNo}
    &engineNoBC=${engineNo}
    &enrollDateBC=${enrollDate}
    &useYearsBC=${useYears}
    &certificateDateBC=
    &enquiryCertificateDate=
    &chgOwnerDateBC=${enrollDate}
    &carVhicleModelBCTemp=
    &relifTaxBrandFlagBC=0
    &sumTonTemp=0.0
    &carKindNameTemp=
    &modelCodeGXBI=${ModelCode}
    &vehicleBrandTemp=${vehicleBrandTemp}
    &madeFactoryBI=${madeFactory}
    &carActualValueBC=${carActualValueBC}
    &car_FlagBC=
    &completeKerbMassMiddleBC=
    &purchasePriceOriginBC=
    &purchasePriceNoTaxFlagBC=
    &carKind=${carKind}
    &brandNameBC=${brandNameBC}
    &modelCodeTemp=${ModelCode}
    &printBrandNameBC=${brandNameBC}
    &mainCarKindCodeBC=${mainCarKindCodeBC}
    &carKindCodeBC=${carKindCodeBC}
    &carKindNameBC=
    &useNatureCodeBC=${useNatureCodeBC}
    &useNatureNameBC=
    &actualValueBC=${actualValueBC}
    &purchasePriceBC=${carActualValueBC}
    &compromisePrice=${actualValueBC}
    &seatCountBC=${seatCountBC}
    &seatCountLBBC=${seatCountBC}
    &tonCountBC=${tonCountBC}
    &tonCountLBBC=${tonCountBC}
    &completeKerbMassNewBC=${completeKerbMassNewBC}
    &exhaustScaleBC=${exhaustScaleBC}
    &exhaustScaleLBBC=${exhaustScaleBC}
    &sumTonCI=
    &licenseKindCodeBC=${licenseKindCodeBC}
    &licenseColorCodeBC=${licenseColorCodeBC}
    &licenseColorNameBC=
    &licenseCategoryBC=${licenseCategoryBC}
    &carTypeCodeBC=${carTypeCodeBC}
    &newFuelModelBC=正常缴税
    &bjModelCodeJy=
    &shModelCodeJy=
    &modelNameBC=
    &modelCodeBC=${modelCodeBC}
    &searchSequenceNoBC=${searchSequenceNoBC}
    &chgOwnerFlagBC=0
    &vinNoBC=
    &checkNoJS=${checkNoJS}
    &pmUseNatureCodeBC=${pmUseNatureCodeBC}
    &checkCodeJS=${checkCodeJS}
    &IsFullEndorBC=0
    &colorCodeBC=01
    &colorNameBC=
    &addonCountBI=
    &addonCountNameBI=
    &loanVehicleFlagBI=0
    &otherNature5BI=
    &carFactoryNameBI=
    &countryNatureBC=A
    &rateCodeBI=20
    &noDamageYearsCI=
    &noDamageYearsBI=
    &otherNature2BI=0
    &runMilesCI=
    &otherNature3BI=0
    &isFullPolicyNoBI=1
    &fuelTypeBC=0
    &vehicleBrandBC=${vehicleBrandBC}
    &VEHICLE_MODELBC=
    &hkLicenseNoBC=
    &makeDateBC=
    &restricFlagLCI=00
    &ecdemicVehicleFlagBI=0
    &tractionTonCountBC=
    &carCertificateNoBC=
    &carCertificateDateBC=
    &CarInfo_Table3CI_Flag=
    &CarInfo_Table3BI_Flag=
    &runMilesAverageBI=40000
    &runAreaCodeBC=04
    &runAreaNameBC=中国境内（不含港、澳、台）
    &safeDeviceBI=1
    &safeDeviceNameBI=
    &noLicenseFlagBI=
    &carUsageBI=
    &carUsageNameBI=
    &lightViolatedBI=
    &seriousViolatedBI=
    &damagedFactorGradeCI=4
    &lViolatedTimesCI=0
    &sViolatedTimesCI=0
    &noClaimFavorTypeBC=1
    &noClaimFavorNameBC=
    &carGoodsTypeBC=
    &carGoodsNameBC=
    &parkingSiteBC=
    &parkingSiteNameBC=
    &addonCountCI=
    &addonCountNameCI=
    &noClaimAdjustReasonBI=
    &lastBusinessNatureBI=
    &noKindAdjustReasonBI=
    &kindAdjustReasonBI=
    &noLoyaltyAdjustReasonBI=
    &selectClauseType_FlagCI=
    &oldClauseTypeCI=F40
    &clauseTypeCI=F40
    &tableOtherNature_Flag=
    &selectClauseType_FlagBI=
    &oldClauseTypeBI=F54
    &clauseTypeBI=F54
    &carInsuredRelationBC=2
    &hkLicenseNo=
    &licenseNo=${licenseNo}
    &stopFlagBC=0
    &sinoSoft0806FlagCI=true
    &strMonth=0
    &licenseNoBCTitle=${licenseNo}
    &newCarFlagBI=0
    &outLandCarFlagBI=
    &isQueryModelCode=1
    &otherNature4CI=1
    &otherNature4BI=1
    &carVhicleModelBC=${carVhicleModelBC}
    &carDealerCodeCI=
    &carName=${carName}
    &pureRiskPremium=${pureRiskPremium}
    &purchasePriceLBBC=${carActualValueBC}
    &ClaimAdjustReasonBI=${ClaimAdjustReasonBI}
    &ClaimAdjustValueBI=${ClaimAdjustValueBI}
    &PeccancyAdjustValueBI=${PeccancyAdjustValueBI}
    &PeccancyAdjustReasonBI=${PeccancyAdjustReasonBI}
    &oldModelCodeBC=${ModelCode}
    &modelCodeGXBC=
    &noticeType=${carVhicleModelBC}
    &pureRiskPremiumFlag=1
    &checkMandatoryLog=1
    &CarDevice_Flag=
    &carDeviceSerialNoBI=
    &carDeviceDeviceNameBI=
    &carDeviceQuantityBI=
    &carDevicePurchasePriceBI=
    &carDeviceBuyDateBI=
    &carDeviceActualValueBI=
    &carDeviceQuantityCountBI=
    &carDevicePurchasePriceCountBI=
    &carDeviceActualValueCountBI=
    &CarInfoCarDevice_FlagBI=
    &CarDriver_Flag=
    &carDriverSerialNoBI=
    &carDriverDriverTypeNamBI=
    &carDriverDriverNameBI=
    &carDriverDrivingLicenseNoBI=
    &carDriverSexBI=1
    &carDriverAgeBI=
    &carDriverMarriageBI=1
    &appliYearBI=1
    &drivingCarTypeBI=
    &carDriverAcceptLicenseDateBI=
    &drivingYearsBI=
    &isDeleteFlagBI=1
    &CarDriver_Flag=
    &carDriverSerialNoBI=
    &carDriverDriverTypeNamBI=
    &carDriverDriverNameBI=
    &carDriverDrivingLicenseNoBI=
    &carDriverSexBI=1
    &carDriverAgeBI=
    &carDriverMarriageBI=1
    &appliYearBI=1
    &drivingCarTypeBI=
    &carDriverAcceptLicenseDateBI=
    &drivingYearsBI=
    &isDeleteFlagBI=1
    &CarDriver_Flag=
    &carDriverSerialNoBI=
    &carDriverDriverTypeNamBI=
    &carDriverDriverNameBI=
    &carDriverDrivingLicenseNoBI=
    &carDriverSexBI=1
    &carDriverAgeBI=
    &carDriverMarriageBI=1
    &appliYearBI=1
    &drivingCarTypeBI=
    &carDriverAcceptLicenseDateBI=
    &drivingYearsBI=
    &isDeleteFlagBI=1
    &CarDriver_Flag=
    &carDriverSerialNoBI=
    &carDriverDriverTypeNamBI=
    &carDriverDriverNameBI=
    &carDriverDrivingLicenseNoBI=
    &carDriverSexBI=1
    &carDriverAgeBI=
    &carDriverMarriageBI=1
    &appliYearBI=1
    &drivingCarTypeBI=
    &carDriverAcceptLicenseDateBI=
    &drivingYearsBI=
    &isDeleteFlagBI=1
    &tableOtherNature_Flag=
    &otherNature1BI=1
    &otherNature1BI=0
    &otherNature6BI=1
    &otherNature6BI=0
    &CarInfoCarDriver_FlagBI=
    &restricFlagCI=
    &preferentialPremiumCI=
    &preferentialFormulaCI=
    &car_markCI=
    &vehicle_typeCI=
    &use_typeCI=
    &rack_noCI=
    &engine_noCI=
    &colorCI=
    &ownerCI=
    &vehicle_register_dateCI=
    &made_dateCI=
    &limit_load_personCI=
    &limit_loadCI=
    &ineffectual_dateCI=
    &made_factoryCI=
    &vehicle_modelCI=
    &vehicle_brand_1CI=
    &vehicle_brand_2CI=
    &vehicle_styleCI=
    &last_check_dateCI=
    &reject_dateCI=
    &statusCI=
    &haulageCI=
    &reInsureFlagCI=${reInsureFlagCI}
    &lastBillDateCI=${lastBillDateCI}
    &useTypeSourceCI=
    &certificateDate_CI=
    &rateFloatFlagCI=
    &claimAdjustReasonCI=
    &peccancyAdjustReasonCI=
    &policySortBC=2
    &isHDflag=
    &proposalNoCI=
    &proposalNoBI=
    &policyNoCI=
    &manualTypeCI=
    &policyNoBI=
    &manualTypeBI=
    &renewalPolicyNoCI=
    &renewalPolicyNoBI=
    &enquiryProposalNoCI=
    &enquiryProposalNoBI=
    &contractNoBC=
    &renewalFlagCI=0
    &renewalFlagBI=0
    &lastPolicyNoCI=
    &lastPolicyNoBI=
    &saleProfessionalNumTempBC=
    &businessNatureArrayBC=
    &channelTypeBC=
    &comCodeBC=03120600
    &comNameBC=淮安中心支公司业务一部
    &handlerCodeBCOffset=淮安中心支公司业务一部
    &handler1CodeBC=03123088
    &handler1NameBC=刘良伟
    &handlerCodeBC=03123088
    &handlerNameBC=刘良伟
    &agentClerkFlagDel=0
    &businessNatureBC=2
    &isPersonal=1
    &saleMobileTemp=202437320830800
    &saleProfessionalNumSDTemp=15052626788
    &agentCodeBC=U03122000011
    &agentNameBC=江苏盛大众联保险代理有限公司淮安分公司
    &OrgCode=
    &agreementNoBC=U03122000011-01
    &shareHolderFlagBC=0
    &shareHolderNameBC=0
    &isInDoorBC=0
    &agriFlagBC=0
    &LifeAgentCodeBC=
    &LifeAgentNameBC=
    &LifeAppContNoCI=
    &LifeAppContNoBI=
    &LifeManageComcodeBC=
    &saleHandlerNameBC=测试单
    &saleMobileBC=202437320830800
    &LifeChannelTypeBC=
    &LifeSaleComCodeBC=
    &SalesCode=
    &SalesName=
    &saleProfessionalNumSDBC=15052626788
    &SalesUserFlag=
    &JudicalCodeBC=
    &groupPurchaseFlagBC=0
    &groupBuySize=
    &visaCodeCI=AJ0507A42009C江苏
    &visaCodeBI=AB0518A22015A
    &printNoCI=
    &printNoBI=
    &manuPrintInputCI=1
    &manuPrintInputBI=
    &manuPolicyInputCI=1
    &manuPolicyInputBI=
    &isHuaKangBC=
    &disRateCIHidden=
    &disRateBIHidden=
    &ALLOW_SPECIALPREMIUM_POLICYCI=2
    &ALLOW_SPECIALPREMIUM_POLICYBI=
    &offset=false
    &inputTimeBC=${inputTimeBC}
    &classCodeBC=05
    &operatorCodeBC=03129002
    &updaterCodeBC=03129002
    &dlfalgBC=false
    &ALLOW_DISPLAY_SPECIALITEMCI=1
    &ALLOW_DISPLAY_SPECIALITEMBI=2
    &Q3_RATE_SWITCHBI=1
    &startUpDateCI=
    &startUpDateBI=
    &startUpDate0802CI=2008-01-31
    &startUpDate0802BI=2008-01-31
    &disCountByRiskCI=0.7
    &disCountByRiskBI=0.7
    &disCountByKindCI=0.7
    &disCountByKindBI=0.7
    &isChangeBaseAmountCI=true
    &isChangeBaseAmountBI=true
    &baseAmountCI=
    &baseAmountBI=${baseAmountBI}
    &comCodeTempBC=03120600
    &comNameTempBC=淮安中心支公司业务一部
    &businessNatureTempBC=2
    &policySortTempBC=2
    &handler1CodeTempBC=03123088
    &handler1NameTempBC=刘良伟
    &agentCodeTempBC=
    &agentNameTempBC=
    &shareHolderFlagTempBC=
    &shareHolderNameTempBC=
    &contractNoTempBC=
    &agreementNoTempBC=
    &groupPurchaseFlagTempBC=
    &otherFlagTempBC=
    &comLevel=3
    &agentClerkFlag=N
    &inputSource=InputSource_New
    &bizNoBC=
    &Check_Com_CheckCode=false
    &motorCadeNatureCI=
    &motorCadeNatureBI=
    &motorCadeCoeffCI=
    &motorCadeCoeffBI=
    &groupCodeBC=
    &shDeclareFlag=
    &shTeamCIFlag=
    &agriFlagBCDefaultValue=
    &SalesRateComSwitch=0
    &isInDoorValue=
    &isPersonalValue=
    &iccardNo=
    &areaBankSWITCH=
    &endorseTypeItemListBC=
    &ciInsureQueryFlagBC=
    &MainHead_Flag=
    &inputRiskChangeCI=0
    &inputRiskChangeBI=0
    &showPG=
    &combinePGM=
    &adjustRateUnder1=false
    &IdentityInfoSC=0
    &appliCustomerTypeBC=1
    &appliNatureBC=${appliNatureBC}
    &unuseField1=
    &appliNameBC=${AppliName}
    &appliCodeBC=
    &appliInsuredCNameBC=
    &appliIdentifyTypeBC=01
    &appliIdNumBC=${IdentifyNumber}
    &appliLinkerNameBC=${AppliName}
    &appliPhoneNumberBC=
    &appliMobileBC=13000000000
    &appliVIPTypeBC=00
    &appliVIPFlagBC=00
    &appliProvinceNameBC=江苏省
    &appliProvincePostCode=08
    &appliCityNameBC=淮安市
    &appliCityPostCode=
    &appliAddressBC=江苏省淮安市
    &appliDetailAddressBC=
    &appliVIPRemarkBC=000
    &customerGroupCodeBC=
    &channelPropertyBC=
    &bankBC=
    &accountNameBC=
    &accountBC=
    &AreaBankNameQuery=0
    &bankCodeBC=
    &bankNameBC=
    &areaProvinceCodeBC=
    &areaProvinceNameBC=
    &areaCodeBC=
    &standardAreaCodeBC=
    &areaNameBC=
    &areaBankCodeBC=
    &areaBankNameBC=
    &PubProvinceFlag=
    &PubAreaFlag=
    &PubBankFlag=
    &PubAccountFlag=
    &PubAmountFlag=
    &PriProvinceFlag=
    &PriAreaFlag=
    &PriBankFlag=
    &PriAccountFlag=
    &PriAmountFlag=
    &remarkInfoBC=
    &appliENameBC=
    &appliEmailBC=
    &Appli_Flag=
    &appliLowerViewFlagHidden=
    &appliLowerViewFlagBC=0
    &appliAddressCNameBC=
    &appliAddressENameBC=
    &appliPostCodeBC=223001
    &unuseField2=
    &insuredCustomerTypeBC=1
    &insuredNatureBC=${insuredNatureBC}
    &insuredNameBC=${AppliName}
    &insuredCodeBC=
    &insuredIdentifyTypeBC=01
    &identifyNumberBC=${IdentifyNumber}
    &insuredLinkerNameBC=${AppliName}
    &insuredPhoneNumberBC=
    &insuredMobileBC=13000000000
    &insuredVIPTypeBC=00
    &insuredVIPFlagBC=00
    &insuredProvinceNameBC=江苏省
    &insuredProvincePostCode=08
    &insuredCityNameBC=淮安市
    &insuredCityPostCode=
    &insuredAddressBC=江苏省淮安市
    &insuredDetailAddressBC=
    &insuredAgeW=44
    &insuredSexBC=1
    &insuredVIPRemarkBC=000
    &insuredAgeBC=
    &insuredJobBC=
    &insuredENameBC=
    &insuredEmailBC=
    &Insured_Flag=
    &insuredNature_FlagBC=
    &insuredLowerViewFlagHidden=
    &insuredLowerViewFlagBC=0
    &insuredAddressCNameBC=
    &insuredAddressENameBC=
    &insuredPostCodeBC=223001
    &focusName=
    &appliNatureBCHidden=
    &insuredNatureBCHidden=
    &groupPurchaseRiskCI=1
    &groupPurchaseRiskBI=0
    &appliSex=
    &changOwnerFlagBC=null
    &showBankFlag=0
    &CentralizedPaySwitch=1
    &appliSexBC=
    &appliNationBC=
    &appliBirthDateBC=
    &appliIssueAuthorityBC=
    &appliValidStartDateBC=
    &appliValidEndDateBC=
    &appliMachineCodeBC=
    &appliCollectFlagBC=
    &insuredSexNewBC=
    &insuredNationBC=
    &insuredBirthDateBC=
    &insuredIssueAuthorityBC=
    &insuredValidStartDateBC=
    &insuredValidEndDateBC=
    &insuredMachineCodeBC=
    &insuredCollectFlagBC=
    &dayW=2017
    &CarInfo_FlagBC=
    &termsSystem=01
    &productSystemValue=机动车
    &chooseFlagBI=
    &profitCodeBI=
    &profitRateBI=
    &profitDetail_ItemKindNoBI=
    &profitDetail_FieldValueBI=
    &profitDetailEncodeBI=
    &profitDetail_FlagBI=
    &profitDetail_ConditionCodeBI=
    &profitDetail_KindCodeBI=
    &profitDetail_RiskCodeBI=
    &profitDetail_ProfitCodeBI=
    &RateProjectNameBI=
    &RateFactorsMaxBI=
    &RateFactorsMinBI=
    &RateContentDescBI=
    &RateProjectCodeBI=
    &UndwrtFactor_KindCodeBI=
    &UndwrtFactor_SerialnoBI=

    &itemKind_FlagBI=
    &withdraw_FlagBI=
    &itemKindNoBI=24
    &kindShortRateBI=
    &mS_FlagBI=S
    &itemKindFlag6FlagBI=
    &itemKindFlag5BI=
    &kindCodeBI=MX
    &kindNameBI=不计免赔率险(新增加设备损失险)
    &modelBI=
    &q3ValueBI=
    &valueTitleBI=每次事故绝对免赔额
    &valueBI=0
    &deductibleRate1TitleBI=绝对免赔系数
    &deductibleRate1BI=1
    &riskLevelTitleBI=绝对免赔率保费优待特约
    &riskLevelBI=0
    &lastCompanyTitleBI=原责任公司
    &lastCompanyBI=1
    &lastAmountTitleBI=原责任限额
    &lastAmountBI=
    &totalProfit1BI=0
    &totalProfit2BI=0
    &itemKind_StartDateBI=
    &itemKind_EndDateBI=
    &itemKindCalculateFlagBI=N
    &itemKindFlag3To4BI=
    &attachFlagBI=A
    &itemKindFlag5FlagBI=0
    &deductibleBI=0
    &deductibleRateBI=0
    &currencyBI=CNY
    &currencyNameBI=人民币
    &currencyNameMainBI=人民币
    &exchangeRateMainBI=
    &preUnitAmountNameBI=
    &unitAmountBI=
    &unitAmountNameBI=元/座
    &quantityBI=
    &quantityNameBI=座
    &amountBI=
    &basePremiumBI=0
    &basePureRiskPremiumBI=
    &rateBI=
    &benchMarkPremiumBI=
    &additionalCostRateBI=${additionalCostRateBI}
    &standardPremiumBI=
    &discountBI=1
    &channelRateBI=${channelRateBI}
    &adjustRateBI=${adjustRateBI}
    &premiumRateBI=0.00%
    &premiumBI=
    &noTaxPremiumBI=
    &taxfeeBI=
    &taxflagBI=
    &taxrateBI=
    &withdrawItemKindNoBI=
    &deductibleSWITCHBI=
    &carClauseChgDateBI=
    &glassTypeModelBI=1_FIELD_SEPARATOR_国产玻璃_GROUP_SEPARATOR_2_FIELD_SEPARATOR_进口玻璃_GROUP_SEPARATOR_3_FIELD_SEPARATOR_特种玻璃_GROUP_SEPARATOR_4_FIELD_SEPARATOR_国产特殊材质_GROUP_SEPARATOR_5_FIELD_SEPARATOR_进口特殊材质
    &agreeTypeModelBI=
    &factoryTypeModelBI=
    &radiusTypeModelBI=
    &minusFlagBI=
    &claimFlagBI=null
    &iSClaimFlagBI=null
    &query_codeBI=${query_codeBI}
    &relievingAreaCodeBI=
    &shortRateFlagBI=2
    &shortRateBI=100.0000

    ${insurance_mix}

    &amountCountBI=0.00
    &basePremiumCountBI=
    &benchMarkPremiumCountBI=0.00
    &additionalCostRateCountBI=
    &standardPremiumCountBI=
    &premiumDisCountBI=0
    &channelRateOfMainBI=1.0000
    &channelLowerRateBI=${channelLowerRateBI}
    &channelTopRateBI=${channelTopRateBI}
    &sumChannelRateBI=${channelRateBI}
    &adjustRateOfMainBI=1.00
    &adjustLowerRateBI=${adjustLowerRateBI}
    &adjustTopRateBI=${adjustTopRateBI}
    &sumAdjustRateBI=${adjustRateBI}
    &sumPremiumBI=${sumPremiumBI}
    &adjustOfMainBI=0
    &sumNoTaxPremiumBI=0.00
    &sumtaxfeeBI=0.00
    &rateFactorsTotalBI=${rateFactorsTotalBI}
    &rateFactorsTotalOriginBI=${rateFactorsTotalOriginBI}
    &rateFactorsTotalMinBI=${rateFactorsTotalMinBI}
    &rateFactorsTotalMaxBI=${rateFactorsTotalMaxBI}
    &deductiblesCoefficient=${deductiblesCoefficient}
    &adjustRateOfC32BI=1
    &checkboxChooseFlagAllBI=
    &adjustRateAllBI=
    &query_sequence_noBI=${query_sequence_noBI}
    &confirm_noBI=
    &QuestionBI=
    &AnswerBI=
    &RenewalFlagBI=
    &isInsureSHBI=0
    &q3_RATE_SWITCH_FlagBI=0
    &RiskInfoItemKind_FlagBI=
    &RateFactorsImfTemp=${RateFactorsImfTemp}
    &rateFactorsTotalBITemp=
    &isRuleCheckTwice=${isRuleCheckTwice}
    &BIDemandFecc_Flag=
    &BIDemandFeccTypeName=
    &BIDemandPeccancy_type=
    &BIDemandPeccancy_name=
    &BIDemandPeccancy_time=
    &BIDemandPeccancy_place=
    &BIDemandPeccancy_code=
    &DecisionCode=
    &feccInfoSize=0
    ${illegal_list}
    &planBI_Flag=
    &payReasonBI=
    &payNoBI=
    &planStartDateBI=
    &planDateBI=
    &prpPlanCurrencyBI=
    &prpPlanCurrencyNameBI=
    &planFeeBI=
    &delinquentFeeBI=
    &realPayFeeBI=
    &NoTaxPremiumBI=
    &taxFeeBI=
    &planOneTimesBI=1
    &payTimesBI=1
    &demandClaim_FlagBI=
    &demandClaimTypeNameBI=
    &demandCompany_noBI=
    &demandClaim_noBI=
    &accidentDeathBI=
    &demandAccident_timeBI=
    &demandEndCase_timeBI=
    &demandClaim_amountBI=
    &claimInfoSize=${claimInfoSize}
    &payRateBI=0
    &lossConditionBI=${lossConditionBI}
    &comLossConditionBI=${comLossConditionBI}
    &lossConditionCodeBI=${lossConditionCodeBI}
    &engageBI_Flag=
    &engageSerialNoBI=
    &clauseCodeBI=
    &clausesBI=
    &clausesContextBI=
    &clauseNameBI=
    &defaultClausesContextBI=
    &engageBI_Flag=
    &engageSerialNoBI=1
    &clauseCodeBI=T00681
    &clausesBI=玻璃特别约定
    &clausesContextBI=本车按国产玻璃承保，出险时按国产玻璃赔付。
    &engageBI_Flag=
    &engageSerialNoBI=2
    &clauseCodeBI=T0059
    &clausesBI=汽车专修厂特别约定
    &clausesContextBI=车损险及车身划痕险选择汽车专修厂：
    &RiskInfoEngage_FlagBI=
    &chooseFlagCI=
    &profitCodeCI=
    &profitRateCI=
    &profitDetail_ItemKindNoCI=
    &profitDetail_FieldValueCI=
    &profitDetailEncodeCI=
    &profitDetail_FlagCI=
    &profitDetail_ConditionCodeCI=
    &profitDetail_KindCodeCI=
    &profitDetail_RiskCodeCI=
    &profitDetail_ProfitCodeCI=
    &kindCodeCI=
    &kindNameCI=
    &itemKindNoCI=
    &mS_FlagCI=
    &totalProfit1CI=0
    &totalProfit2CI=0
    &itemKindCalculateFlagCI=
    &itemKind_StartDateCI=
    &itemKind_EndDateCI=
    &deductibleCI=
    &deductibleRateCI=
    &itemKindFlag3To4CI=
    &itemKindFlag5FlagCI=
    &itemKindFlag6FlagCI=2
    &currencyCI=CNY
    &currencyNameCI=人民币
    &itemKind_FlagCI=
    &withdraw_FlagCI=
    &attachFlagCI=
    &rateCI=
    &amountCI=
    &benchMarkPremiumCI=
    &basePremiumCI=0
    &discountCI=1
    &adjustRateCI=1.00
    &premiumRateCI=100%
    &premiumCI=
    &noTaxPremiumCI=
    &taxfeeCI=
    &taxRateCI=
    &taxflagCI=
    &relievingAreaCodeCI=
    &shortRateFlagCI=2
    &shortRateCI=100.0000
    &limit_FlagCI=
    &limitGradeCI=
    &limitNoCI=
    &prpLimitCurrencyCI=
    &prpLimitCurrencyNameCI=
    &limitTypeCI=
    &limitTypeNameCI=
    &limitFeeCI=
    &limit_FlagCI=
    &limitGradeCI=2
    &limitNoCI=1
    &prpLimitCurrencyCI=CNY
    &prpLimitCurrencyNameCI=人民币
    &limitTypeCI=90
    &limitTypeNameCI=死亡伤残赔偿限额
    &limitFeeCI=110000.00
    &limit_FlagCI=
    &limitGradeCI=2
    &limitNoCI=1
    &prpLimitCurrencyCI=CNY
    &prpLimitCurrencyNameCI=人民币
    &limitTypeCI=91
    &limitTypeNameCI=医疗费用赔偿限额
    &limitFeeCI=10000.00
    &limit_FlagCI=
    &limitGradeCI=2
    &limitNoCI=1
    &prpLimitCurrencyCI=CNY
    &prpLimitCurrencyNameCI=人民币
    &limitTypeCI=92
    &limitTypeNameCI=财产损失赔偿限额
    &limitFeeCI=2000.00
    &limit_FlagCI=
    &limitGradeCI=2
    &limitNoCI=1
    &prpLimitCurrencyCI=CNY
    &prpLimitCurrencyNameCI=人民币
    &limitTypeCI=93
    &limitTypeNameCI=无责任死亡伤残赔偿限额
    &limitFeeCI=11000.00
    &limit_FlagCI=
    &limitGradeCI=2
    &limitNoCI=1
    &prpLimitCurrencyCI=CNY
    &prpLimitCurrencyNameCI=人民币
    &limitTypeCI=94
    &limitTypeNameCI=无责任医疗费用赔偿限额
    &limitFeeCI=1000.00
    &limit_FlagCI=
    &limitGradeCI=2
    &limitNoCI=1
    &prpLimitCurrencyCI=CNY
    &prpLimitCurrencyNameCI=人民币
    &limitTypeCI=95
    &limitTypeNameCI=无责任财产损失赔偿限额
    &limitFeeCI=100.00
    &kindCodeCI=BZ
    &kindNameCI=机动车交通事故责任强制险
    &itemKindNoCI=1
    &mS_FlagCI=M
    &totalProfit1CI=0
    &totalProfit2CI=0
    &itemKindCalculateFlagCI=Y
    &itemKind_StartDateCI=
    &itemKind_EndDateCI=
    &deductibleCI=
    &deductibleRateCI=
    &itemKindFlag3To4CI=
    &itemKindFlag5FlagCI=
    &itemKindFlag6FlagCI=2
    &currencyCI=CNY
    &currencyNameCI=人民币
    &itemKind_FlagCI=
    &withdraw_FlagCI=
    &attachFlagCI=
    &rateCI=
    &amountCI=
    &benchMarkPremiumCI=
    &basePremiumCI=0
    &discountCI=1
    &adjustRateCI=1.00
    &premiumRateCI=100%
    &premiumCI=
    &noTaxPremiumCI=
    &taxfeeCI=
    &taxRateCI=
    &taxflagCI=
    &amountCountCI=
    &benchMarkPremiumCountCI=
    &premiumDisCountCI=
    &adjustRateOfMainCI=1
    &premiumRateCI=100%
    &sumPremiumCI=${sumPremiumCI}
    &sumNoTaxPremiumCI=
    &sumtaxfeeCI=
    &checkboxChooseFlagAllCI=
    &adjustRateAllCI=
    &query_sequence_noCI=${query_sequence_noCI}
    &confirm_noCI=
    &QuestionCI=
    &AnswerCI=
    &RenewalFlagCI=
    &RiskInfoItemKind_FlagCI=
    &query_codeCI=${query_codeCI}
    &planCI_Flag=
    &payReasonCI=
    &payNoCI=
    &planStartDateCI=
    &planDateCI=
    &prpPlanCurrencyCI=
    &prpPlanCurrencyNameCI=
    &planFeeCI=
    &delinquentFeeCI=
    &realPayFeeCI=
    &NoTaxPremiumCI=
    &taxFeeCI=
    &planOneTimesCI=1
    &payTimesCI=1
    &CIDemandClaim_Flag=
    &CIDemandClaimTypeName=
    &CIDemandCompany_no=
    &CIDemandClaim_no=
    &CIAccidentDeath=
    &CIDemandAccident_time=
    &CIDemandEndCase_time=
    &CIDemandClaim_amount=
    &payRateCI=0
    &lossConditionCI=
    &comLossConditionCI=${comLossConditionCI}
    &lossConditionCodeCI=
    &engageCI_Flag=
    &engageSerialNoCI=
    &clauseCodeCI=
    &clausesCI=
    &clausesContextCI=
    &clauseNameCI=
    &defaultClausesContextCI=
    &engageCI_Flag=
    &engageSerialNoCI=1
    &clauseCodeCI=T0080
    &clausesCI=全国客户须知特别约定
    &clausesContextCI=尊敬的客户：投保次日起，您可通过本公司网站http：//www.cindapcic.com、客服电话4008 667788、营业网点核实保单及理赔信息。若对查询结果有异议，请及时通过网站留言或客服电话联系本公司。
    &engageCI_Flag=
    &engageSerialNoCI=2
    &clauseCodeCI=T0028
    &clausesCI=车主约定
    &clausesContextCI=被保险人与行驶证车主不符：被保险人为保费试算，行驶证车主为${AppliName}。
    &RiskInfoEngage_FlagCI=
    &CarShipTax_Flag=
    &taxItemCodeCS=
    &taxItemNameCS=
    &taxItemDetailCodeCS=
    &taxItemDetailNameCS=
    &extendChar1CS=
    &taxPrintNoCS=
    &taxpayerIdentifierCS=${IdentifyNumber}
    &taxpayerNameCS=${AppliName}
    &taxRelifFlagCS=1
    &relifReasonCS=01
    &baseTaxationCS=1
    &taxReliefCS=
    &freeRateCS=
    &paidCertificateCS=
    &taxComNameCS=
    &taxComCodeCS=
    &taxStartDateCS=
    &taxEndDateCS=
    &completeKerbMassCS=${completeKerbMassNewBC}
    &licenseCategoryCS=${licenseCategoryBC}
    &taxRelifFlagCICS=
    &taxRelifFlagNameCICS=
    &taxAmendPremiumCICS=
    &taxAmendDeclareCICS=
    &taxFlagCICS=
    &calcTaxFlagCI=
    &taxComCodeCICS=
    &leviedDateCICS=
    &taxpayerIdentifierCICS=
    &taxpayerNameCICS=
    &taxRegistryNumberCICS=
    &taxDueCICS=
    &relifReasonCICS=
    &relifReasonNameCICS=
    &baseTaxationCICS=
    &baseTaxationNameCICS=
    &taxReliefCICS=
    &freeRateCICS=
    &paidCertificateCICS=
    &taxComNameCICS=
    &taxStartDateCICS=
    &taxEndDateCICS=
    &taxActualCICS=
    &previousPayCICS=
    &lateFeeCICS=
    &sumTaxCICS=
    &taxUnitCS=
    &CIDemandFecc_Flag=
    &CIDemandFeccTypeName=
    &CIDemandPeccancy_time=
    &CIDemandPeccancy_place=
    &CIDemandPeccancy_code=
    &CIDemandPeccancy_desc=
    &CIDemandAdjust_rate=
    &CIDemandPeccancy_type=
    &CIDemandCerti_type=
    &CIDemandCerti_code=
    &CIDemandLossAccept_date=
    &Customer_Flag=
    &inQuiryNoBC=${inQuiryNoBC}
    &riskLevelFlag=${riskLevelFlag}
    &businessClassBC=${businessClassBC}
    &businessClassNameBC=${businessClassNameBC}
    &sellingExpensesRateBI=${sellingExpensesRateBI}
    &sellingExpensesRateCI=${sellingExpensesRateCI}
    &BusinessRemark1=${BusinessRemark1}
    &expensesBC_Flag=
    &sellRateCI=${sellRateCI}
    &chargeNumberCI=${chargeNumberCI}
    &businessCategoryCI=${businessCategoryCI}
    &expenses_FlagCI=
    &maxDisRateCI=0.0
    &disRateCI=${disRateCI}
    &commissionRateUpperCI=
    &premiumDisRateCI=
    &sumFeeCI=${sumFeeCI}
    &sumNoTaxFeeCI=${sumNoTaxFeeCI}
    &VATtaxRateCI=${VATtaxRateCI}
    &VATbillingTypeCI=
    &VATNoTaxPremium1CI=
    &maxSalesSalaryRateCI=
    &salesSalaryRateCI=
    &premiumSalesSalaryCI=0.00
    &VATdutyRatioCI=${VATdutyRatioCI}
    &VATtransferTaxCI=${VATtransferTaxCI}
    &expensesFlag2CI=2
    &maxManageFeeRateCI=
    &maxExpenseRateCI=
    &manageFeeRateCI=0
    &maxAllowanceRateCI=0.0
    &allowanceRateCI=
    &premiumAllowanceRateCI=
    &maxBusinessPromoteRateCI=0.0
    &businessPromoteRateCI=
    &premiumBusinessPromoteRateCI=
    &sellRateBI=${sellRateBI}
    &chargeNumberBI=${chargeNumberBI}
    &businessCategoryBI=${businessCategoryBI}
    &expenses_FlagBI=
    &maxDisRateBI=0.0
    &disRateBI=
    &premiumDisRateBI=
    &sumFeeBI=0.00
    &sumNoTaxFeeBI=0.00
    &maxSalesSalaryRateBI=0.0
    &salesSalaryRateBI=0.0
    &premiumSalesSalaryBI=0.00
    &VATtaxRateBI=${VATtaxRateBI}
    &VATbillingTypeBI=
    &VATNoTaxPremium1BI=
    &VATdutyRatioBI=${VATdutyRatioBI}
    &VATtransferTaxBI=${VATtransferTaxBI}
    &expensesFlag2BI=1
    &maxManageFeeRateBI=0.0000
    &maxExpenseRateBI=
    &manageFeeRateBI=0
    &commissionRateUpperBI=
    &maxAllowanceRateBI=0.0
    &allowanceRateBI=0.0
    &premiumAllowanceRateBI=0.00
    &maxBusinessPromoteRateBI=0.0
    &businessPromoteRateBI=0.0
    &premiumBusinessPromoteRateBI=0.0
    &changePremiumDisRateCI=
    &changePremiumDisRateBI=
    &pureRateCI=0.0
    &pureRateBI=0.0
    &disRate1CI=0.0
    &premiumDisRate1CI=0.0
    &disRate1BI=0.0
    &premiumDisRate1BI=0.0
    &changePremiumDisRate1CI=0.00
    &changePremiumDisRate1BI=0.00
    &configPowerManageFeeRateCI=1
    &configPowerMiddleCostCI=0
    &configPowerManageFeeRateBI=0
    &configPowerMiddleCostBI=0
    &personPowerManageFeeRateBC=1
    &personPowerMiddleCostBC=0
    &fundRateCI=
    &fundAmountCI=

    &coefficient1CI=0.0
    &coefficient2CI=0.0
    &coefficient3CI=0.0
    &coefficient4CI=0.0
    &coefficient5CI=0.0
    &coefficient6CI=0.0
    &coefficient7CI=0.0
    &coefficient8CI=0.0
    &coefficient9CI=0.0
    &coefficient10CI=0.0
    &coefficient11CI=0.0
    &attribute1CI=0.0000
    &attribute2CI=0.0000
    &attribute3CI=0.0000
    &attribute4CI=0.0000
    &attribute5CI=0.0000
    &attribute1BI=0.0000
    &attribute2BI=0.0000
    &attribute3BI=0.0000
    &attribute4BI=0.0000
    &attribute5BI=0.0000
    &coefficient1BI=0.0
    &coefficient2BI=0.0
    &coefficient3BI=0.0
    &coefficient4BI=0.0
    &coefficient5BI=0.0
    &coefficient6BI=0.0
    &coefficient7BI=0.0
    &coefficient8BI=0.0
    &coefficient9BI=0.0
    &coefficient10BI=0.0
    &coefficient11BI=0.0

    &disrateYCI=null
    &allowancerateYCI=null
    &teammaintenancerateYCI=null
    &businesspromoterateYCI=null
    &displayrateYCI=null
    &othermarketrateYCI=null

    &sumbudgetYCI=${sumbudgetYCI}

    &disrateYBI=null
    &allowancerateYBI=null
    &teammaintenancerateYBI=null
    &businesspromoterateYBI=null
    &displayrateYBI=null
    &othermarketrateYBI=null

    &sumbudgetYBI=${sumbudgetYBI}
    &personPowerDisRateNoShowBC=true
    &personPowerDisRateNoModifyBC=true
    &OtherTable_Flag=
    &ProposalNoCI=
    &ProposalNoBI=
    &contractNoImage=
    &shTeamCIFlag=
    &shDeclareQueryFlag=
    &InputType=
    &RepPolicyNo=
    &groupCode=
    &checkboxAssess=
    &mainRemarkBC=
    &argueSolutionBC=1
    &arbitBoardCodeBC=
    &arbitBoardNameBC=
    &saleNameBC=
    &saleProfessionalNumBC=
    &carCheckStatusBC=1
    &carCheckerBC=
    &carCheckerNameBC=
    &carCheckTimeBC=
    &reinsFlagBI=0
    &reinsFlagCI=0
    &uniteBusinessFlag=0
    &OtherInfo_FlagBC=
    &U02030010001=50000
    &U0203001sumpremium=100
    &U02030010003=50000
    &U02030010004=50000
    &U0203001103=5000
    &U0203001102=5000
    &U0203001108=1000
    &U0203001111=80000
    &Address_Flag=
    &AddressNo=
    &ProvincePostCode=
    &CityPostCode=
    &AddressCode=
    &ProvinceAddressName=
    &CityAddressName=
    &PostAddressName=
    &AddressName=
    &AddressNum=0
    &U02270010001=100000
    &U0227001sumpremium=100
    &U02270010002=20000
    &U02270010006=20元/天
    &U02270020001=50000
    &U0227002sumpremium=100
    &U02270020003=10000
    &U02270020004=10元/天
    &U02270030001=400000
    &U0227003sumpremium=100
    &U02270030002=200000
    &U02270030003=100000
    &U02270030004=50000
    &tempSaveFlag=${tempSaveFlag}
    &tempProposalNoCI=${tempProposalNoCI}
    &tempProposalNoBI=${tempProposalNoBI}
    &relationKindCode=-B-MB-A-MA-D3-MD3-D4-MD4-G1-MG1-L-ML-F-T1-Z-MZ-D2-MD2-X3-MX3-R1-MR1-X-MX-Q4-Q5-Q6-I
'''
    startDateCI = permium_dict.get('jq_insuranceEndTime', getlatedate(1))  # JQ险
    endDateCI = getlatedate(364, startDateCI)
    immeValidStartDateCI = startDateCI  # 当天
    immeValidEndDateCI = endDateCI
    operateDateCI = getlatedate(0)
    checkPayStartDate = getlatedate(1)
    startDateBI = permium_dict.get('sy_insuranceEndTime', getlatedate(1))  # getlatedate(1)
    endDateBI = getlatedate(364, startDateBI)
    immeValidStartDateBI = startDateBI  #
    immeValidEndDateBI = endDateBI
    currentDate = getlatedate(0)  # 当前时间
    AppliName = permium_dict['vehicle']['carOwnerBC']  # 保险人
    carOwnerNature1BC = permium_dict['vehicle']['carOwnerNature1BC']  # 个人 还是企业
    carOwnerIdentifyTypeCI = permium_dict['vehicle']['carOwnerIdentifyTypeCI']  # 身份证 还是机构
    IdentifyNumber = "350582197312034538"
    licenseNo = permium_dict['vehicle']['licenseNoBC']
    frameNo = permium_dict['vehicle']['frameNoBC']
    engineNo = permium_dict['vehicle']['EngineNo']
    completeKerbMassNewBC = permium_dict['vehicle']['completeKerbMassNewBC']  # 整备质量
    enrollDate = permium_dict['vehicle']['enrollDateBC']

    ModelCode = permium_dict['carVinInfo']['BrandCode']  # "DZABCD0020"
    vehicleBrandTemp = permium_dict['vehicle']['vehicleBrandTemp']
    madeFactory = permium_dict['vehicle']['madeFactoryBI']
    vehicleBrandBC = permium_dict['vehicle']['madeFactoryBI']  # "上汽大众"
    carVhicleModelBC = permium_dict['vehicle']['vehicle_modelCI']
    carActualValueBC = permium_dict['carVinInfo']['compromisePrice']  # "109800.0"  # 新车价格
    useYears = permium_dict.get("actualValue", {}).get("useYears", "6")
    carKind = permium_dict.get("actualValue", {}).get("carKind", "")  # "轿车类"
    brandNameBC = permium_dict['carVinInfo']['brandNameBC']  # "朗逸SVW7167GSD轿车"
    actualValueBC = permium_dict.get("actualValue", {}).get("actualValueBC", "0")  # 协商价格
    baseAmountBI = format_number(actualValueBC)
    mainCarKindCodeBC = permium_dict['carVinInfo']['mainCarKindCodeBC']  # "A"车辆大类
    carKindCodeBC = permium_dict['carVinInfo']['carKindCodeBC']  # "A0"#车辆种类
    useNatureCodeBC = permium_dict['carVinInfo']['useNatureCodeBC']  # "8A"#使用性质
    exhaustScaleBC = permium_dict['vehicle']['exhaustScaleBC']  # "1.598"
    licenseKindCodeBC = permium_dict['vehicle']['licenseKindCodeBC']  # "02"  # 车辆类型
    licenseColorCodeBC = "01"
    if licenseKindCodeBC == "01":
        # 大型车车黄色底牌
        licenseColorCodeBC = "04"
    # 组织结构或者自然人
    appliNatureBC = permium_dict['vehicle']['appliNatureBC']
    insuredNatureBC = permium_dict['vehicle']['insuredNatureBC']
    licenseCategoryBC = permium_dict['vehicle']['licenseCategoryBC']  # "K33"
    carTypeCodeBC = permium_dict['vehicle']['carTypeCodeBC']  # "1"
    # modelCodeBC = permium_dict.get("SubmitBI",{}).get("modelCodeBC","") #"BSHCLZUC0009"
    modelCodeBC = permium_dict.get("actualValue", {}).get("modelCodeBC", "")  # "BSHCLZUC0009"
    searchSequenceNoBC = permium_dict.get("actualValue", {}).get("searchSequenceNoBC", "")  # "BSHCLZUC000971A1"
    checkNoJS = permium_dict['vehicle']['CheckNoJS']  # "72XDCX320017001494930693163516"
    # pmUseNatureCodeBC = "A"
    pmUseNatureCodeBC = permium_dict['vehicle']['pmUseNatureCodeBC']
    checkCodeJS = permium_dict['vehicle']['CheckCodeJS']  # "KXCV"
    carName = permium_dict['carVinInfo']['carclassName']  # "朗逸SVW7167GSD 品悠进享版"
    pureRiskPremium = permium_dict.get("actualValue", {}).get("riskPremium", "")  # 风险保费 请求车辆实际价格的时候带出的
    seats = permium_dict['vehicle']['seatCountBC']
    if seats == "0" or seats == "":
        seats = permium_dict['vehicle']['seatCountBC']
        permium_dict['vehicle']['seatCountBC'] = seats
    seatCountBC = seats
    tonCountBC = permium_dict['vehicle']['tonCountBC']
    inputTimeBC = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # 当前时间 精确到秒


    # 第二个请求与第一个请求的区别的参数 第一个请求为空 第二个请求带值
    claimInfoSize = permium_dict.get("SubmitBI", {}).get("claimInfoSize", "0")  # "0"
    ClaimAdjustReasonBI = permium_dict.get("SubmitBI", {}).get("ClaimAdjustReasonBI", "")  # "无赔款优待-连续2年没有发生赔款"
    ClaimAdjustValueBI = permium_dict.get("SubmitBI", {}).get("ClaimAdjustValueBI", "")  # "-0.3"
    PeccancyAdjustValueBI = permium_dict.get("SubmitBI", {}).get("PeccancyAdjustValueBI", "")  # "-0.3"
    PeccancyAdjustReasonBI = permium_dict.get("SubmitBI", {}).get("PeccancyAdjustReasonBI",
                                                                  "")  # "累计违法系数不超过5%或仅存在不上浮的违法行为，不浮动"

    query_codeBI = permium_dict.get("SubmitBI", {}).get("query_codeBI", "")
    query_sequence_noBI = permium_dict.get("SubmitBI", {}).get("query_sequence_noBI", "")
    query_sequence_noCI = permium_dict.get("query_sequence_noCI", "")
    lossConditionBI = permium_dict.get("SubmitBI", {}).get("lossConditionBI", "")
    comLossConditionBI = permium_dict.get("SubmitBI", {}).get("comLossConditionBI", "")
    lossConditionCodeBI = permium_dict.get("SubmitBI", {}).get("lossConditionCodeBI", "")  # "02"
    comLossConditionCI = permium_dict.get("SubmitBI", {}).get("comLossConditionCI", "")  # "2年未出险"
    # 违法信息
    illegal_list = permium_dict.get("SubmitBI", {}).get("illegal_list", "")

    # 第三个请求 需要费率
    additionalCostRateBI = permium_dict.get("Rules", {}).get("additionalCostRateBI", "")
    channelRateBI = permium_dict.get("Rules", {}).get("channelRateBI", "0.8500")
    adjustRateBI = permium_dict.get("Rules", {}).get("adjustRateBI", "0.8500")
    adjustTopRateBI = permium_dict.get("Rules", {}).get("adjustTopRateBI", "")
    adjustLowerRateBI = permium_dict.get("Rules", {}).get("adjustLowerRateBI", "")
    channelLowerRateBI = permium_dict.get("Rules", {}).get("channelLowerRateBI", "1.0000")
    channelTopRateBI = permium_dict.get("Rules", {}).get("channelTopRateBI", "")
    sumChannelRateBI = permium_dict.get("Rules", {}).get("sumChannelRateBI", "0.8500")
    sumAdjustRateBI = permium_dict.get("Rules", {}).get("sumAdjustRateBI", "0.8500")

    rateFactorsTotalBI = permium_dict.get("Rules", {}).get("rateFactorsTotalBI", "")
    rateFactorsTotalOriginBI = permium_dict.get("Rules", {}).get("rateFactorsTotalOriginBI", "0.7225")
    rateFactorsTotalMinBI = permium_dict.get("Rules", {}).get("rateFactorsTotalMinBI", "")
    rateFactorsTotalMaxBI = permium_dict.get("Rules", {}).get("rateFactorsTotalMaxBI", "")
    deductiblesCoefficient = permium_dict.get("Rules", {}).get("deductiblesCoefficient", "")
    RateFactorsImfTemp = permium_dict.get("Rules", {}).get("RateFactorsImfTemp", "")
    # 获取交强险返回信息
    query_codeCI = permium_dict.get("JQ", {}).get("query_codeCI", "")
    reInsureFlagCI = permium_dict.get("JQ", {}).get("reInsureFlagCI", "")
    lastBillDateCI = permium_dict.get("JQ", {}).get("lastBillDateCI", "")
    isRuleCheckTwice = "4"
    # 使用 |_| 分割
    RateFactorslist = ""
    if RateFactorsImfTemp != "":
        RateFactorslist = parse_split_str(RateFactorsImfTemp)
        permium_dict['Rules']["RateFactorslist"] = RateFactorslist

    insuranceType = permium_dict['insuranceType']
    insurance_mix = get_xd_insurance(insuranceType, permium_dict)


    # 发送保单暂存
    tempSaveFlag = permium_dict.get("tempSaveFlag", "0")

    tempProposalNoCI = permium_dict.get("tmpBICI", {}).get("tempProposalNoCI", "")
    tempProposalNoBI = permium_dict.get("tmpBICI", {}).get("tempProposalNoBI", "")

    # 传入保费
    sumPremiumBI = ""  # 商业险总保费
    sumPremiumCI = ""
    sumPremiumBI_list = permium_dict.get("sy_premuim", [])
    if len(sumPremiumBI_list) != 0:
        sumPremiumBI = sumPremiumBI_list[0].get("sum_premium", "0")

    sumPremiumCI = permium_dict.get("JQ", {}).get("compulsory_insurance", "")
    riskLevelFlag = permium_dict.get("riskLevel", {}).get("riskLevelFlag", "")
    #VATdutyRatioCI = permium_dict.get("riskLevel", {}).get("VATdutyRatioCI", "0.00")
    #VATdutyRatioBI = permium_dict.get("riskLevel", {}).get("VATdutyRatioBI", "")
    VATdutyRatioCI=VATdutyRatioBI=1.06
    VATtaxRateBI = permium_dict.get("riskLevel", {}).get("VATtaxRateBI", "0.00")
    VATtransferTaxCI = permium_dict.get("riskLevel", {}).get("VATtransferTaxCI", "0.00")
    sellRateBI = permium_dict.get("riskLevel", {}).get("sellRateBI", "")
    sellingExpensesRateCI = permium_dict.get("riskLevel", {}).get("sellingExpensesRateCI", "")
    chargeNumberCI = permium_dict.get("riskLevel", {}).get("chargeNumberCI", "")
    sumbudgetYCI = permium_dict.get("riskLevel", {}).get("sumbudgetYCI", "")
    sumNoTaxFeeCI = permium_dict.get("riskLevel", {}).get("sumNoTaxFeeCI", "")
    businessCategoryBI = permium_dict.get("riskLevel", {}).get("businessCategoryBI", "")
    BusinessRemark1 = permium_dict.get("riskLevel", {}).get("BusinessRemark1", "")
    businessClassBC = permium_dict.get("riskLevel", {}).get("businessClassBC", "")
    sumbudgetYBI = permium_dict.get("riskLevel", {}).get("sumbudgetYBI", "")
    chargeNumberBI = permium_dict.get("riskLevel", {}).get("chargeNumberBI", "")
    sellingExpensesRateBI = permium_dict.get("riskLevel", {}).get("sellingExpensesRateBI", "")
    sumFeeCI = permium_dict.get("riskLevel", {}).get("sumFeeCI", "")
    businessClassNameBC = permium_dict.get("riskLevel", {}).get("businessClassNameBC", "")
    VATtransferTaxBI = permium_dict.get("riskLevel", {}).get("VATtransferTaxBI", "")
    sellRateCI = permium_dict.get("riskLevel", {}).get("sellRateCI", "")
    inQuiryNoBC = permium_dict.get("riskLevel", {}).get("inQuiryNoBC", "")
    VATtaxRateCI = permium_dict.get("riskLevel", {}).get("VATtaxRateCI", "")
    businessCategoryCI = permium_dict.get("riskLevel", {}).get("businessCategoryCI", "")
    disRateCI = permium_dict.get("riskLevel", {}).get("disRateCI", "")

    body = Template(body)
    body = body.substitute(currentDate=currentDate, startDateCI=startDateCI, endDateCI=endDateCI,
                           operateDateCI=operateDateCI, checkPayStartDate=checkPayStartDate,
                           immeValidStartDateCI=immeValidStartDateCI, immeValidEndDateCI=immeValidEndDateCI,
                           startDateBI=startDateBI, endDateBI=endDateBI,
                           immeValidStartDateBI=immeValidStartDateBI,
                           immeValidEndDateBI=immeValidEndDateBI,
                           AppliName=AppliName, IdentifyNumber=IdentifyNumber, licenseNo=licenseNo,
                           carOwnerIdentifyTypeCI=carOwnerIdentifyTypeCI,
                           carOwnerNature1BC=carOwnerNature1BC,
                           frameNo=frameNo, licenseColorCodeBC=licenseColorCodeBC,
                           engineNo=engineNo, enrollDate=enrollDate, useYears=useYears, ModelCode=ModelCode,
                           vehicleBrandTemp=vehicleBrandTemp, madeFactory=madeFactory,
                           completeKerbMassNewBC=completeKerbMassNewBC,
                           vehicleBrandBC=vehicleBrandBC,
                           carVhicleModelBC=carVhicleModelBC, carActualValueBC=carActualValueBC,
                           carKind=carKind,
                           brandNameBC=brandNameBC, actualValueBC=actualValueBC, baseAmountBI=baseAmountBI,
                           mainCarKindCodeBC=mainCarKindCodeBC, appliNatureBC=appliNatureBC,
                           carKindCodeBC=carKindCodeBC, useNatureCodeBC=useNatureCodeBC,
                           insuredNatureBC=insuredNatureBC,
                           exhaustScaleBC=exhaustScaleBC,
                           licenseKindCodeBC=licenseKindCodeBC, licenseCategoryBC=licenseCategoryBC,
                           carTypeCodeBC=carTypeCodeBC,
                           modelCodeBC=modelCodeBC, searchSequenceNoBC=searchSequenceNoBC,
                           checkNoJS=checkNoJS,
                           pmUseNatureCodeBC=pmUseNatureCodeBC, checkCodeJS=checkCodeJS, carName=carName,
                           pureRiskPremium=pureRiskPremium,
                           seatCountBC=seatCountBC, tonCountBC=tonCountBC, inputTimeBC=inputTimeBC,

                           ClaimAdjustReasonBI=ClaimAdjustReasonBI, ClaimAdjustValueBI=ClaimAdjustValueBI,
                           PeccancyAdjustReasonBI=PeccancyAdjustReasonBI, claimInfoSize=claimInfoSize,
                           query_codeBI=query_codeBI, query_sequence_noBI=query_sequence_noBI,
                           query_sequence_noCI=query_sequence_noCI,
                           lossConditionBI=lossConditionBI, comLossConditionBI=comLossConditionBI,
                           lossConditionCodeBI=lossConditionCodeBI, comLossConditionCI=comLossConditionCI,
                           PeccancyAdjustValueBI=PeccancyAdjustValueBI, illegal_list=illegal_list,

                           additionalCostRateBI=additionalCostRateBI, channelRateBI=channelRateBI,
                           adjustLowerRateBI=adjustLowerRateBI,
                           adjustRateBI=adjustRateBI, channelLowerRateBI=channelLowerRateBI,
                           adjustTopRateBI=adjustTopRateBI,
                           channelTopRateBI=channelTopRateBI, sumChannelRateBI=sumChannelRateBI,
                           sumAdjustRateBI=sumAdjustRateBI, rateFactorsTotalBI=rateFactorsTotalBI,
                           rateFactorsTotalOriginBI=rateFactorsTotalOriginBI,
                           rateFactorsTotalMinBI=rateFactorsTotalMinBI, rateFactorsTotalMaxBI=rateFactorsTotalMaxBI,
                           deductiblesCoefficient=deductiblesCoefficient, RateFactorsImfTemp=RateFactorsImfTemp,
                           isRuleCheckTwice=isRuleCheckTwice, RateFactorslist=RateFactorslist,
                           insurance_mix=insurance_mix, tempSaveFlag=tempSaveFlag, tempProposalNoCI=tempProposalNoCI,
                           tempProposalNoBI=tempProposalNoBI,

                           query_codeCI=query_codeCI, lastBillDateCI=lastBillDateCI, reInsureFlagCI=reInsureFlagCI,
                           riskLevelFlag=riskLevelFlag, sumPremiumBI=sumPremiumBI, sumPremiumCI=sumPremiumCI,

                           VATdutyRatioCI=VATdutyRatioCI, VATtransferTaxCI=VATtransferTaxCI, sellRateBI=sellRateBI,
                           VATtaxRateBI=VATtaxRateBI, sellingExpensesRateCI=sellingExpensesRateCI,
                           chargeNumberCI=chargeNumberCI,
                           sumbudgetYCI=sumbudgetYCI, sumNoTaxFeeCI=sumNoTaxFeeCI,
                           businessCategoryBI=businessCategoryBI, VATdutyRatioBI=VATdutyRatioBI,
                           VATtaxRateCI=VATtaxRateCI, BusinessRemark1=BusinessRemark1, businessClassBC=businessClassBC,
                           sumbudgetYBI=sumbudgetYBI,
                           chargeNumberBI=chargeNumberBI, sellingExpensesRateBI=sellingExpensesRateBI,
                           sumFeeCI=sumFeeCI, businessClassNameBC=businessClassNameBC,
                           VATtransferTaxBI=VATtransferTaxBI, sellRateCI=sellRateCI, inQuiryNoBC=inQuiryNoBC,
                           businessCategoryCI=businessCategoryCI,disRateCI=disRateCI

                           )
    body = body.replace("\n", "").replace(" ", "")
    return urllib.quote(body.encode('gbk'), safe='=,&')


if __name__ == "__main__":
    permium_dict = {}
    permium_dict['vehicle'] = {}
    permium_dict['vehicle']['CheckNoJS'] = ""
    permium_dict['vehicle']['CheckCodeJS'] = ""
    print xd_get_first_body(permium_dict)
